[package]
name = "pulse-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.27.6"
serde = { version = "1.0.144", features = ["derive"] }
rmp-serde = "1.1.2"